#!/usr/bin/env python3
"""Regenerate a package manifest from the import.json of a verified image import.

    adimport --image <the package's image> --dest <scratch>
    python importer/gen_known_files.py <scratch>/win/import.json                    (Deluxe: version 1)
    python importer/gen_known_files.py <scratch>/win/packages/<id>/import.json      (any other package: version 2)

writes known_files.inc (Deluxe) or known_files_<id>.inc next to this script.

A manifest is what lets adimport verify a folder source (a mounted disc, a
copy of one, copied floppies) file by file, where there is no image to hash.
Only an import whose image md5 is the package's known image is accepted as
the reference, so a manifest can never be seeded from a damaged or different
pressing. It holds paths, sizes and md5s only -- never After Dark bytes, and
never the AD 3.x archive password (import.json does not hold it either).
"""
import json
import os
import re
import sys

# packages.cc: each package's known image (kXxxImages) and its root.
PACKAGES = {
    "deluxe": ("d875a60338b73f44b7befa06bdd33aeb", "FILES", ("AD40", "CLASSIC", "ENGINE", "AFI")),
    "ad10": ("a8d088415d391ce0d3199a831e1b2ad6", "packages/ad10", ("AD10TH", "ENGINE", "AFI")),
    "ad32": ("8b8be6977375fbf4d54146b9d505aa1c", "packages/ad32", ("AD32", "ENGINE")),
    "tt": ("541b9cfd744c377263a4ab1a144bdc12", "packages/tt", ("TWISTED", "ENGINE")),
    "simpsons": ("7674adbda6fc5402d4e7a78af14880cc", "packages/simpsons", ("SIMPSONS", "ENGINE")),
}

DELUXE_HEADER = """\
// Manifest of ADE/FILES/{AD40,CLASSIC,ENGINE,AFI} on the After Dark 4.0 Deluxe
// CD (image md5 %s): {path relative to <assets>\\win, size, md5}.
// Sizes and hashes only -- no After Dark bytes. GENERATED by
// gen_known_files.py from the import.json of an import of that image; do not
// edit by hand.
"""

PACKAGE_HEADER = """\
// Manifest of package "%s" (%s) as adimport installs it from the image with
// md5 %s: {path relative to <assets>\\win, size, md5}, fix-up copies
// included. Sizes and hashes only -- no After Dark bytes. GENERATED by
// gen_known_files.py from the import.json of an import of that image; do not
// edit by hand.
"""

# 8.3 names as the sources list them; the fix-up copies (PACKAGES.md §4.3)
# keep the long names the modules open ("Flying Toasters.mid").
COMPONENT = re.compile(r"[A-Za-z0-9_!#$%&'()@^`{}~. -]+")


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_known_files.py <import.json of a verified image import>")
    with open(sys.argv[1], encoding="utf-8") as f:
        j = json.load(f)
    src = j.get("source", {})
    if j.get("version") == 1:
        pid = "deluxe"
        image_md5 = src.get("isoMd5")
        title = "After Dark 4.0 Deluxe"
    elif j.get("version") == 2:
        pkg = j.get("package", {})
        pid = pkg.get("id")
        image_md5 = src.get("imageMd5")
        title = pkg.get("title", pid)
        if pid not in PACKAGES or pid == "deluxe":
            sys.exit("refusing: unknown package %r" % pid)
        if pkg.get("root") != PACKAGES[pid][1]:
            sys.exit("refusing: package root %r, expected %r" % (pkg.get("root"), PACKAGES[pid][1]))
    else:
        sys.exit("refusing: import.json version %r" % j.get("version"))
    known_md5, root, dirs = PACKAGES[pid]
    if image_md5 != known_md5:
        sys.exit("refusing: import.json's image md5 is %r, not the %s image %s" % (image_md5, pid, known_md5))
    if j.get("verified") != "image":
        sys.exit("refusing: import.json says verified %r, not \"image\"" % j.get("verified"))
    files = sorted(j["files"], key=lambda f: f["path"])
    seen = set()
    for f in files:
        p = f["path"]
        parts = p.split("/")
        prefix = root.split("/")
        if parts[:len(prefix)] != prefix or len(parts) < len(prefix) + 2 or parts[len(prefix)] not in dirs:
            sys.exit("unexpected path %r" % p)
        for c in parts[len(prefix):]:
            if c in (".", "..") or not COMPONENT.fullmatch(c) or c.endswith((" ", ".")):
                sys.exit("unexpected path %r" % p)
        if not re.fullmatch(r"[0-9a-f]{32}", f["md5"]) or p.upper() in seen or not isinstance(f["size"], int):
            sys.exit("bad entry %r" % f)
        seen.add(p.upper())
    name = "known_files.inc" if pid == "deluxe" else "known_files_%s.inc" % pid
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), name)
    with open(out, "w", encoding="utf-8", newline="\n") as w:
        if pid == "deluxe":
            w.write(DELUXE_HEADER % known_md5)
        else:
            w.write(PACKAGE_HEADER % (pid, title, known_md5))
        for f in files:
            w.write('{"%s", %d, "%s"},\n' % (f["path"], f["size"], f["md5"]))
    print("wrote %d entries to %s" % (len(files), out))


if __name__ == "__main__":
    main()
