#include "packages.h"

#include "importer.h"

namespace adw::import {

namespace {

// ---- manifests (generated by gen_known_files.py; sizes and md5s only) --------------

const KnownFile kDeluxeKnown[] = {
#include "known_files.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kAd10Known[] = {
#include "known_files_ad10.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kAd32Known[] = {
#include "known_files_ad32.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kTtKnown[] = {
#include "known_files_tt.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kSimpsonsKnown[] = {
#include "known_files_simpsons.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kSwseKnown[] = {
#include "known_files_swse.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kStartrekKnown[] = {
#include "known_files_startrek.inc"
    {nullptr, 0, nullptr},
};

template <size_t N>
std::span<const KnownFile> manifest(const KnownFile (&a)[N]) {
  return std::span<const KnownFile>(a, N - 1);
}

// ---- deluxe ------------------------------------------------------------------------------

// The md5s of two setup pictures, read from the known images: ADE\PAGE1.BMP
// on the Deluxe CD (28198 bytes, 118x226) and INSTALL\SETUP.BMP on the
// Totally Twisted CD (49314 bytes, 387x251).
constexpr char kDeluxePage1Md5[] = "945259b85a1f0a5e0aedfad53561c838";
constexpr char kTtSetupBmpMd5[] = "3e5eee81009de2a2a432cfabf5d7cfea";

const char* const kDeluxeModuleDirs[] = {"AD40", "ENGINE", "CLASSIC"};
const KnownImage kDeluxeImages[] = {
    {kDeluxeIsoMd5, 400234496, "ISO-9660, Mac/PC hybrid CD", "AD_DELUXE"},
};
const Download kDeluxeDownloads[] = {
    {kDeluxeIsoUrl, kDeluxeIsoFileName, 400234496, kDeluxeIsoMd5, "image"},
};
// Without these three engines neither lane can run anything.
const char* const kDeluxeRequired[] = {"AD40/ADXPL510.DLL", "CLASSIC/ADXPL300.DLL", "ENGINE/OLDMOD16.DLL"};
// The folders under ADE\FILES the hosts use (WALLPAPR is desktop wallpaper).
const char* const kDeluxeCopy[] = {"AD40", "CLASSIC", "ENGINE", "AFI"};

// ---- ad10 --------------------------------------------------------------------------------

const char* const kAd10ModuleDirs[] = {"AD10TH", "ENGINE"};
const KnownImage kAd10Images[] = {
    {"a8d088415d391ce0d3199a831e1b2ad6", 150228992, "ISO-9660 + Joliet, Mac/PC hybrid CD", "AD10TH"},
};
// The only exact copy online (darkened once, restored 2024-07-19).
const Download kAd10Downloads[] = {
    {"https://archive.org/download/ad10th/ad10th.iso", L"ad10th.iso", 150228992, "a8d088415d391ce0d3199a831e1b2ad6",
     "image"},
};
const char* const kAd10Required[] = {"AD10TH/ADXPL510.DLL", "AD10TH/ADXPL300.DLL", "AD10TH/ADXPL40.DLL",
                                     "ENGINE/OLDMOD16.DLL", "ENGINE/AD_SND.DLL",   "ENGINE/AFTERDAR.SCR"};
// GAMES (standalone game EXEs) and WALLPAPR are not screen savers.
const char* const kAd10Copy[] = {"AD10TH", "ENGINE", "AFI"};
// Deluxe's FILES has an AD40; the 10th Anniversary's has none.
const char* const kAd10Absent[] = {"AD40"};
// What the original installers did and the modules depend on (SETUP.INF and
// ENGINE\PREVIOUS.INF): ADXPL40 loads TT_SND.DLL from the AD Data Files root
// only, and the Toasters 2k builds open their music by its installed long
// names.
const Fixup kAd10Fixups[] = {
    {"AD10TH/TT_SND.DLL", "AD10TH/MUSIC/TT_SND.DLL"},
    {"AD10TH/MUSIC/Toasters2k.mid", "AD10TH/TOASTER1.MID"},
    {"AD10TH/MUSIC/Flying Toasters.mid", "AD10TH/TOASTERS.MID"},
    {"AD10TH/MUSIC/Baby Toasters.mid", "AD10TH/BABY.MID"},
};
// An earlier build that SETUP.INF never installs; it would otherwise share
// the installed TOASTER2.AD's name.
const NameOverride kAd10Names[] = {
    {"AD10TH/TOAST2K.AD", "Toasters 2k (early build)"},
};

// ---- ad32 --------------------------------------------------------------------------------

const char* const kAd32ModuleDirs[] = {"AD32"};
const KnownImage kAd32Images[] = {
    {"8b8be6977375fbf4d54146b9d505aa1c", 61693952, "ISO-9660, Mac/PC hybrid CD", "ADW320_C"},
};
// Three byte-identical copies, one file name: the curated one first, the
// uncurated upload last.
const Download kAd32Downloads[] = {
    {"https://archive.org/download/after-dark-v3_2/"
     "After%20Dark%203.2%20%281995%29%28Berkeley%20Systems%29%5BMac-PC%5D.iso",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
    {"https://archive.org/download/berkeley-systems-after-dark-for-windows/berkeley-systems-after-dark-for-windows.iso",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
    {"https://archive.org/download/3x-2634d-923b-452be-6e-0210afa-3547b-9469-after-dark-3.2-nirvana/ADW320_C.ISO",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
};
const char* const kAd32Required[] = {"AD32/ADXPL300.DLL", "ENGINE/AD_SND.DLL", "ENGINE/ADTASK.DLL"};

// ---- tt ----------------------------------------------------------------------------------

const char* const kTtModuleDirs[] = {"TWISTED"};
const KnownImage kTtImages[] = {
    {"541b9cfd744c377263a4ab1a144bdc12", 39784448, "ISO-9660, Mac/PC hybrid CD", "TTW320CD"},
};
const Download kTtDownloads[] = {
    {"https://archive.org/download/TTW320CD/TTW320CD.ISO", L"TTW320CD.ISO", 39784448, "541b9cfd744c377263a4ab1a144bdc12",
     "image"},
};
const char* const kTtRequired[] = {"TWISTED/ADXPL40.DLL", "TWISTED/TT_SND.DLL", "ENGINE/AD_SND.DLL",
                                   "ENGINE/ADTASK.DLL"};

// ---- simpsons ----------------------------------------------------------------------------

const char* const kSimpsonsModuleDirs[] = {"SIMPSONS"};
const KnownImage kSimpsonsImages[] = {
    {"7674adbda6fc5402d4e7a78af14880cc", 2949120, "FAT12 2.88 MB floppy image (both install disks)", ""},
};
// No image of the floppies exists online (the known image is the owner's own
// merge of both disks, with their notes): two ZIPs of the 28 install files,
// every one md5-identical to the floppies' (the readme CHANGES.TXT, which
// the recipe never reads, is missing). Different bytes, so different names.
const Download kSimpsonsDownloads[] = {
    {"https://archive.org/download/SIMPSONS_WIN/SIMPSONS.zip", L"SIMPSONS.zip", 2752575,
     "90a85bf64c971fe65045f1afc6db0eba", "zip"},
    {"https://archive.org/download/AfterDarkSimpsons/After%20Dark%20-%20The%20Simpsons.zip",
     L"After Dark - The Simpsons.zip", 2752010, "1d6083344b16f09e61acf016eca25026", "zip"},
};
const char* const kSimpsonsRequired[] = {"SIMPSONS/ADXPL310.DLL", "SIMPSONS/SIMP_SND.DLL", "ENGINE/AD_SND.DLL",
                                         "ENGINE/ADTASK.DLL"};
// The 15 module archives, spread over both install floppies.
const char* const kSimpsonsArchives[] = {"BURNS.ZIP",    "CHALKBRD.ZIP", "CLOCKS.ZIP",  "GRAFFITI.ZIP", "GRANDPA.ZIP",
                                         "GRASSKRT.ZIP", "HOMEREAT.ZIP", "HOW2DRAW.ZIP", "INS.ZIP",     "KRUSTY.ZIP",
                                         "MLISA.ZIP",    "PHYSICS.ZIP",  "SFILES.ZIP",  "SNOWBALL.ZIP", "STRIVIA.ZIP"};

// ---- swse --------------------------------------------------------------------------------
//
// Star Wars Screen Entertainment (LucasArts, 1994; by Presage Software) is not
// an After Dark release: its 14 modules are Intermission IMX modules (16-bit
// NE DLLs exporting SAVERINIT/SAVERDRAW, driven by Intermission's IMX reader
// IMIMXPLY.IMQ). The disc is a CD copy of the five install floppies: Presage's
// INSTALL.EXE + INSTALL.DAT, multi-volume ARJ archives and SZDD-compressed
// loose files (research/win/pkg/swse, gitignored).

const char* const kSwseModuleDirs[] = {"SAVER"};
// The CD, and the Redump dump of the same pressing (raw 2352-byte sectors;
// cooked, its first 3529 sectors are that ISO byte for byte).
const KnownImage kSwseImages[] = {
    {"bfa63c1bce15dcbea965dfd7c2ed44e8", 7227392, "ISO-9660 CD of the five install disks", "SWSE"},
    {"ce51614a3484b9269b5ed9e61510e971", 9005808, "the same CD as raw 2352-byte sectors (Redump)", "SWSE"},
};
// The exact ISO; the Redump BIN of it; a flat ZIP of the disc's 40 files,
// each md5-identical to the disc's (verified 2026-09-28:
// research/win/pkg/swse/sources.json). Three files, three names.
const Download kSwseDownloads[] = {
    {"https://archive.org/download/cd_AfterDark_Star_Wars_ScreenSaver_for_Win3.1/AfterDarkStarWars.iso",
     L"AfterDarkStarWars.iso", 7227392, "bfa63c1bce15dcbea965dfd7c2ed44e8", "image"},
    {"https://archive.org/download/swse1/SWSE.bin", L"Star Wars - Screen Entertainment (USA).bin", 9005808,
     "ce51614a3484b9269b5ed9e61510e971", "image"},
    {"https://archive.org/download/swse_20240317/SWSE.zip", L"SWSE.zip", 7013137, "c7a4c5322a784a3e88964c5a7f499226",
     "zip"},
};
// Every install disk: SWSE1.ARJ is disk 1; SWSE2.ARJ and .A01-.A03 are one
// archive over disks 2-5 (INSTALL.DAT [disks]).
const char* const kSwseArchives[] = {"SWSE1.ARJ", "SWSE2.ARJ", "SWSE2.A01", "SWSE2.A02", "SWSE2.A03"};
// What every module loads (INTRMLIB -> ANTSW; SWSE.DLL -> MEMMIDI, SWSFX),
// the IMX reader, and the modules' default settings.
const char* const kSwseRequired[] = {"SAVER/INTRMLIB.DLL", "SAVER/ANTSW.DLL",    "SAVER/SWSE.DLL",
                                     "SAVER/READJPG.DLL",  "SAVER/STRESS.DLL",   "SAVER/SWSFX.DLL",
                                     "SAVER/MEMMIDI.DLL",  "ENGINE/IMIMXPLY.IMQ", "WINDOWS/SWSE.INI"};
// INSTALL.DAT lines 4, 10-13 and 37: STRESS.DLL beside the modules, the
// General MIDI set (CHECK=24) under the names the modules open, directly in
// the module folder as the installer put them in C:\SAVER, and the default
// settings, which it put in C:\WINDOWS.
const LooseFile kSwseLoose[] = {
    {"STRESS.DL_", "SAVER/STRESS.DLL", Codec::szdd},    {"GM_BATTL.MI_", "SAVER/BATTLE.MID", Codec::szdd},
    {"GM_CNTNA.MI_", "SAVER/CANTINA.MID", Codec::szdd}, {"GM_EMPIR.MI_", "SAVER/EMPIRE.MID", Codec::szdd},
    {"GM_TITLE.MI_", "SAVER/SWTHEME.MID", Codec::szdd}, {"SWSE.INI", "WINDOWS/SWSE.INI", Codec::plain},
};
// The names SAVERINIT returns (the modules' SWSE.INI sections); no resource
// holds them.
const NameOverride kSwseNames[] = {
    {"SAVER/BATTLES.IMX", "Space Battles"},    {"SAVER/BIOS.IMX", "Character Biographies"},
    {"SAVER/BLUPRINT.IMX", "Blueprints"},      {"SAVER/CANTINA.IMX", "Cantina"},
    {"SAVER/HYPERSPC.IMX", "Hyperspace"},      {"SAVER/ICLOCK.IMX", "Imperial Clock"},
    {"SAVER/JAWAS.IMX", "Jawas"},              {"SAVER/POSTERS.IMX", "Poster Art"},
    {"SAVER/RCLOCK.IMX", "Rebel Clock"},       {"SAVER/SABRDUEL.IMX", "Lightsaber Duel"},
    {"SAVER/STORYBRD.IMX", "Storyboards"},     {"SAVER/SWTEXT.IMX", "Scrolling Text"},
    {"SAVER/TRENCH.IMX", "Death Star Trench"}, {"SAVER/VADER.IMX", "Darth Vader"},
};

// ---- startrek ----------------------------------------------------------------------------
//
// Star Trek: The Screen Saver ("After Dark, Version 2.0b - The Star Trek
// Edition", Berkeley Systems, 1992): 16 After Dark 2.0 modules (16-bit NE DLLs
// exporting MODULE, the Classic lane) on two 1.44 MB floppies installed by
// Microsoft Setup 2.0, nearly every file KWAJ-compressed (kwaj.h). The recipe
// is ST_NSTLL.INF and AD_NSTLL.MST baked into a table: SETUP.LST is read only
// to identify the release (research/win/pkg/startrek, gitignored).

// The modules' own folder: the installer's C:\AFTERDRK, which the 16-bit lane
// mounts there (the modules find ST_RES\ and SOUNDS\ below AD_PREFS.INI's
// [After Dark] Path).
const char* const kStartrekModuleDirs[] = {"AFTERDRK"};
// The Internet Archive's two images (item afterdark-20b_startrek, also what
// the user's ZIP holds), and the same disks as a Windows 9x copy wrote to them
// (item startrektosscreensaver1992win: the boot sector's OEM name and
// root-directory access dates differ; every file is the same byte for byte).
// A release on two disks: only a set of both is the release.
const KnownImage kStartrekImages[] = {
    {"28e33608b8d3bafa28585472c4a7a9ac", 1474560, "FAT12 1.44 MB floppy image, install disk 1 of 2", "", 1},
    {"c630da5f6839303b599947f56fdd7c25", 1474560, "FAT12 1.44 MB floppy image, install disk 2 of 2", "", 2},
    {"6ee71b45e32b07001d46ab8c80af589d", 1474560,
     "FAT12 1.44 MB floppy image, install disk 1 of 2 (a copy Windows 9x wrote to)", "", 1},
    {"af9d29a7ddea2c03618899c1c5733c67", 1474560,
     "FAT12 1.44 MB floppy image, install disk 2 of 2 (a copy Windows 9x wrote to)", "", 2},
};
// Both copies are images of both disks (verified 2026-09-29:
// research/win/pkg/startrek/importer/sources.json); each part is checked
// against its published size and md5. Other bytes, other names. (The user's
// own ZIP is the Internet Archive's on-the-fly ZIP of the first item, whose
// md5 changes with every download: it is identified by its images' md5s.)
const DownloadPart kStartrekDisk2[] = {
    {"https://archive.org/download/afterdark-20b_startrek/afterdark-20b_startrek_disk2.img",
     L"afterdark-20b_startrek_disk2.img", 1474560, "c630da5f6839303b599947f56fdd7c25"},
};
const DownloadPart kStartrekDisk2Win9x[] = {
    {"https://archive.org/download/startrektosscreensaver1992win/startrek2.img", L"startrek2.img", 1474560,
     "af9d29a7ddea2c03618899c1c5733c67"},
};
const Download kStartrekDownloads[] = {
    {"https://archive.org/download/afterdark-20b_startrek/afterdark-20b_startrek_disk1.img",
     L"afterdark-20b_startrek_disk1.img", 1474560, "28e33608b8d3bafa28585472c4a7a9ac", "image", kStartrekDisk2},
    {"https://archive.org/download/startrektosscreensaver1992win/startrek1.img", L"startrek1.img", 1474560,
     "6ee71b45e32b07001d46ab8c80af589d", "image", kStartrekDisk2Win9x},
};
// What the modules cannot run without: their framework (AD_MOD, AD_RSRC), the
// art and sound databases AD_MOD opens from <Path>ST_RES\, and the sound
// library the native bridge loads.
const char* const kStartrekRequired[] = {
    "AFTERDRK/AD_MOD.DLL",          "AFTERDRK/AD_RSRC.DLL",       "AFTERDRK/ST_RES/ST_RESDB.DLL",
    "AFTERDRK/ST_RES/ST_MASKS.DLL", "AFTERDRK/ST_RES/ST_VGA.DLL", "AFTERDRK/ST_RES/ST_SVGA.DLL",
    "AFTERDRK/ST_RES/ST_SND.DLL",   "ENGINE/AD_SND.DLL"};
// Every install disk: the tag files of ST_NSTLL.INF [Source Media
// Descriptions] (disk 1's is the fingerprint's, beside SETUP.LST).
const char* const kStartrekDiskTags[] = {"MISSION.AD_", "ST_SND.DL_"};
// ST_NSTLL.INF and AD_NSTLL.MST, flattened: what the modules use, nothing
// edited. The modules and their DLLs in the module folder, as installed in
// C:\AFTERDRK (the installer put AD_MOD and AD_RSRC in C:\WINDOWS; the
// modules import them, so they sit beside them, invariant I2); the
// multimedia sound driver AD_SND loads from there ([Sound] SoundDriver);
// ST_RES\ and SOUNDS\ below it (Sounder refuses to load without a .WAV);
// AD_SND 1.0 and the pristine AD.EXE in ENGINE (the host replaces AD.EXE, which
// is kept for reference as INTERMIS.EXE is; nothing loads it). Never
// installed: the disk's AD_PREFS.INI (its SoundDriver=AD_MPT.DRV would win
// over the lane's seed and hang the emulator), the PC-speaker path
// (AD_MPT.DRV, SPALETTE.DLL, AD_LIB.DLL), AD_SB.DRV (it refuses Windows 3.1
// and later), the network password DLLs and utility, AD.386, AD_WRAP.COM,
// AFTERDRK.NSS, ADINIT.EXE, AD.HLP, AD_MESG.ADS (the data of a Messages module
// this release does not ship) and every setup file.
const LooseFile kStartrekLoose[] = {
    {"BRAINCEL.AD_", "AFTERDRK/BRAINCEL.AD", Codec::kwaj},
    {"COMMS.AD_", "AFTERDRK/COMMS.AD", Codec::kwaj},
    {"FINAL.AD_", "AFTERDRK/FINAL.AD", Codec::kwaj},
    {"FRONTIER.AD_", "AFTERDRK/FRONTIER.AD", Codec::kwaj},
    {"HORTA.AD_", "AFTERDRK/HORTA.AD", Codec::kwaj},
    {"IONSTORM.AD_", "AFTERDRK/IONSTORM.AD", Codec::kwaj},
    {"MISSION.AD_", "AFTERDRK/MISSION.AD", Codec::kwaj},
    {"PANELS.AD_", "AFTERDRK/PANELS.AD", Codec::kwaj},
    {"PLANETS.AD_", "AFTERDRK/PLANETS.AD", Codec::kwaj},
    {"SCOTTYS.AD_", "AFTERDRK/SCOTTYS.AD", Codec::kwaj},
    {"SICKBAY.AD_", "AFTERDRK/SICKBAY.AD", Codec::kwaj},
    {"SOUNDER.AD_", "AFTERDRK/SOUNDER.AD", Codec::kwaj},
    {"SPACE.AD_", "AFTERDRK/SPACE.AD", Codec::kwaj},
    {"SPOCK.AD_", "AFTERDRK/SPOCK.AD", Codec::kwaj},
    {"THOLIAN.AD_", "AFTERDRK/THOLIAN.AD", Codec::kwaj},
    {"TRIBBLE.AD_", "AFTERDRK/TRIBBLE.AD", Codec::kwaj},
    {"AD_MOD.DL_", "AFTERDRK/AD_MOD.DLL", Codec::kwaj},
    {"AD_RSRC.DL_", "AFTERDRK/AD_RSRC.DLL", Codec::kwaj},
    {"AD_MME.DR_", "AFTERDRK/AD_MME.DRV", Codec::kwaj},
    {"ST_RESDB.DL_", "AFTERDRK/ST_RES/ST_RESDB.DLL", Codec::kwaj},
    {"ST_MASKS.DL_", "AFTERDRK/ST_RES/ST_MASKS.DLL", Codec::kwaj},
    {"ST_VGA.DL_", "AFTERDRK/ST_RES/ST_VGA.DLL", Codec::kwaj},
    {"ST_SVGA.DL_", "AFTERDRK/ST_RES/ST_SVGA.DLL", Codec::kwaj},
    {"ST_SND.DL_", "AFTERDRK/ST_RES/ST_SND.DLL", Codec::kwaj},
    {"JIM.WA_", "AFTERDRK/SOUNDS/JIM.WAV", Codec::kwaj},
    {"AD_SND.DL_", "ENGINE/AD_SND.DLL", Codec::kwaj},
    {"AD.EX_", "ENGINE/AD.EXE", Codec::kwaj},
};
// PLANETS.AD's name resource says " PlanetaryAtlas"; its About heading and
// Berkeley's own later PREVIOUS.INF (After Dark 4.0 Deluxe) say "Planetary
// Atlas".
const NameOverride kStartrekNames[] = {
    {"AFTERDRK/PLANETS.AD", "Planetary Atlas"},
};

// ---- box covers (COVERS.md §2.3) ------------------------------------------------------------
//
// Only URLs, md5s, sizes, paths and crops: the pictures are fetched (md5- and
// size-checked) or read from the disc being imported onto the user's machine,
// never shipped. The research behind each row is in
// research/win/pkg/covers/<id>/cover.json (gitignored).

using CK = CoverSource::Kind;

// A download source: an https URL as published, the md5 and size of the file.
constexpr CoverSource cover_download(const char* art, const char* label, const char* credit, const char* url,
                                     const char* md5, uint64_t size, const wchar_t* file_name, Crop crop = {}) {
  return CoverSource{CK::download, art, label, credit, url, md5, size, file_name, nullptr, nullptr, 0, 0, crop};
}
// A picture on the source being imported (resource 2 = an NE/PE RT_BITMAP).
constexpr CoverSource cover_disc(const char* art, const char* label, const char* credit, const char* path,
                                 const char* path_md5, Crop crop = {}, uint16_t resource_type = 0,
                                 uint16_t resource_id = 0) {
  return CoverSource{CK::disc, art, label, credit, nullptr, nullptr, 0, nullptr, path, path_md5, resource_type,
                     resource_id, crop};
}

// Deluxe: the box front from Berkeley Systems' own product page (1997, through
// the Wayback Machine; 162x195, and a tile is never shown larger than 160x200),
// else the setup wizard's portrait art on the disc, else the Internet
// Archive's scan of the disc label (the same item as the ISO).
const CoverSource kDeluxeCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113325id_/"
                   "http://www.berksys.com:80/products/afterdark/box.deluxe.gif",
                   "abb5ea84262cc6a2badea016f69cc7e8", 19460, L"berksys_box.deluxe.gif"),
    cover_disc("panel", "Setup art", "your disc", "ADE/PAGE1.BMP", kDeluxePage1Md5),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/after-dark-4-deluxe/disc.jpg",
                   "0b5104351ae6fa60da6d48164e8f548e", 737758, L"after-dark-4-deluxe_disc.jpg"),
};
// 10th Anniversary: the disc-label scan in the ISO's item, else the setup
// wizard's art (pages 1-6 are byte-identical). The box art the user owns has
// no downloadable copy: it becomes the cover only through --set-cover.
const CoverSource kAd10Covers[] = {
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/ad10th/01_ad10_cd.jpg",
                   "e1e77b74ccc9bcd4e5b818f841f0614d", 376876, L"ad10th_01_ad10_cd.jpg"),
    cover_disc("panel", "Setup art", "your disc", "ADE/PAGE1.BMP", "30f247d08fe8a4fd394658a3c4564a06"),
};
// 3.2: no box scan of 3.0 or 3.2 exists; the installer splash comes first,
// cropped above its warning and copyright rows, then two scans of the label.
const CoverSource kAd32Covers[] = {
    cover_disc("splash", "Installer art", "your disc", "INSTALL/SETUP.BMP", "67e76581f69bcfdb62ef1c7ff61fc426",
               Crop{0, 0, 387, 183}),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/after-dark-v3_2/disc.jpg",
                   "68f2aad89dcdc1fdbcb3419ab42077f9", 349982, L"after-dark-v3_2_disc.jpg"),
    cover_download("disc", "Disc label", "Internet Archive",
                   "https://archive.org/download/berkeley-systems-after-dark-for-windows/"
                   "berkeley-systems-after-dark-for-windows.png",
                   "f2fdf32138f96da06f8d348af059d712", 1857714, L"berkeley-systems-after-dark-for-windows.png"),
};
// Totally Twisted: the box front from Berkeley Systems' product page (1997,
// through the Wayback Machine; 127x162, the retail box's art), else the box
// front of Sierra's later edition from The Sierra Chest (through the Wayback
// Machine; 498x599), else the installer splash, cropped above its warning
// text, else the TTW320CD item's TIFF scan of the disc (2840x2888).
const CoverSource kTtCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113451id_/"
                   "http://www.berksys.com:80/products/afterdark/box.twistedL.jpg",
                   "5aa9478d761a580f1d9006ee41d0cd3f", 26382, L"berksys_box.twistedL.jpg"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20230422055429id_/"
                   "https://www.sierrachest.com/gfx/games/AfterDarkTotallyTwisted/box/01_front.JPG",
                   "3f87e84e3d86d7a2d6f96c86a8102452", 53679, L"sierrachest_AfterDarkTotallyTwisted_01_front.jpg"),
    cover_disc("splash", "Installer art", "your disc", "INSTALL/SETUP.BMP", kTtSetupBmpMd5, Crop{0, 0, 387, 204}),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/TTW320CD/TTW320CD.tif",
                   "ec19d74fd2ac46d4bc8f6021ad0011e6", 24632572, L"TTW320CD.tif"),
};
// The Simpsons: the box front (Fox's art: fetched onto the user's machine
// only, never bundled), from Wikisimpsons, else the Wayback Machine's copy of
// the full-box scan it was cut from; else the installer splash in SETUP.EXE.
const CoverSource kSimpsonsCovers[] = {
    cover_download("box", "Box front", "Wikisimpsons",
                   "https://static.simpsonswiki.com/images/7/72/The_Simpsons_Screen_Saver.png",
                   "47f4619da9e79b126a4fb45770f0e649", 1011608, L"The_Simpsons_Screen_Saver.png"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20250715075938id_/"
                   "https://www.whipassgaming.com/images/deadsections/mac/simpsonsfullbox.jpg",
                   "94db22db1e89b3ff2fdb97e610056602", 484234, L"simpsonsfullbox.jpg", Crop{0, 0, 600, 776}),
    cover_disc("splash", "Installer art", "your disks", "SETUP.EXE", "980867b7ab5394b09adad725d375ba95",
               Crop{0, 0, 387, 172}, 2, 7500),
};

// Star Wars Screen Entertainment: the box front from Presage's own product
// page (1997, through the Wayback Machine; 150x200), else Wookieepedia's photo
// of the same US box (the Wayback Machine's byte-exact capture of the stored
// original: Fandom's live URL rewrites what it serves), else two archive.org
// scans of the disc label, the second cropped to the disc. LucasArts' art:
// fetched onto the user's machine only, never bundled. The disc itself has no
// picture a disc source can reach (every one is inside the ARJ archives).
const CoverSource kSwseCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970310054846id_/"
                   "http://www.presage.com:80/images/pimages/box-starwars.JPEG",
                   "8b84792a21f3a21e09cc2809d263d9c1", 30600, L"presage_box-starwars.jpg"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20221205171117id_/"
                   "https://static.wikia.nocookie.net/starwars/images/9/9a/SWScreenEntertainment.jpg/revision/latest",
                   "dc4e541d1a79a46747caf0cb6f425c0a", 190239, L"wookieepedia_SWScreenEntertainment.jpg"),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/swse1/1.jpg",
                   "a40d11a61ee0288048bdfdd28e48e57c", 2156659, L"swse1_1.jpg"),
    cover_download("disc", "Disc label", "Internet Archive",
                   "https://archive.org/download/cd_AfterDark_Star_Wars_ScreenSaver_for_Win3.1/"
                   "AfterDark%20Star%20Wars%20-%20CD.jpg",
                   "b8ac25eb20a87f44e47ff8ed097698d7", 948614, L"cd_AfterDark_Star_Wars_ScreenSaver_for_Win3.1_CD.jpg",
                   Crop{20, 14, 1424, 1424}),
};

// Star Trek: The Screen Saver: the Windows retail box front from the
// Internet Archive's box scans (item afterdark-20b_startrek_box, 1180x1525:
// it fills the tile), else the same front at 600 dpi, else the scan of disk
// 1's label in the disk images' own item (drawn as a picture, never cut to a
// disc: it is a floppy's). Paramount's and Berkeley's art: fetched onto the
// user's machine only, never bundled. The disks have no picture a disc source
// can reach (every one is KWAJ-compressed).
const CoverSource kStartrekCovers[] = {
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/afterdark-20b_startrek_box/Aaa_itemimage.jpg",
                   "157eb04fcc9bdc0d4a831148ca6cc260", 577239, L"afterdark-20b_startrek_box_Aaa_itemimage.jpg"),
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/afterdark-20b_startrek_box/"
                   "After%20Dark%202.0b%20-%20Star%20Trek%20-%20Box%20-%20Front.jpg",
                   "f41d1dbdaadaeeb0f9bc0a6aa76754ce", 9277274, L"After Dark 2.0b - Star Trek - Box - Front.jpg"),
    cover_download("panel", "Disk label", "Internet Archive",
                   "https://archive.org/download/afterdark-20b_startrek/afterdark-20b_startrek_disk1.jpg",
                   "dbda3bc66b809f446a17138073579b53", 569964, L"afterdark-20b_startrek_disk1.jpg"),
};

const Package kPackages[] = {
    {"deluxe", "After Dark 4.0 Deluxe", "Deluxe", Recipe::tree, "FILES", kDeluxeModuleDirs, kDeluxeImages,
     kDeluxeRequired, kDeluxeCopy, nullptr, {}, nullptr, nullptr, nullptr, {}, {}, {}, manifest(kDeluxeKnown),
     kDeluxeDownloads, kDeluxeCovers, "1996-10"},  // disc mastered 1996-10-12; modules dated 1996-09
    {"ad10", "After Dark 10th Anniversary", "10th Anniversary", Recipe::tree, "packages/ad10", kAd10ModuleDirs,
     kAd10Images, kAd10Required, kAd10Copy, "AD10TH/ADXPL40.DLL", kAd10Absent, nullptr, nullptr, nullptr, {},
     kAd10Fixups, kAd10Names, manifest(kAd10Known), kAd10Downloads, kAd10Covers, "1999-09"},  // disc mastered 1999-09-06
    {"ad32", "After Dark 3.2", "After Dark 3.2", Recipe::ad3zip, "packages/ad32", kAd32ModuleDirs, kAd32Images,
     kAd32Required, {}, nullptr, {}, "AD32", "ADXPL300.DLL", "AD3.AFI", {}, {}, {}, manifest(kAd32Known),
     kAd32Downloads, kAd32Covers, "1995-08-02"},  // newest file on the disc (its PVD date is a bogus 1993)
    {"tt", "Totally Twisted After Dark", "Totally Twisted", Recipe::ad3zip, "packages/tt", kTtModuleDirs, kTtImages,
     kTtRequired, {}, nullptr, {}, "TWISTED", "ADXPL40.DLL", "PHLEM.AFI", {}, {}, {}, manifest(kTtKnown),
     kTtDownloads, kTtCovers, "1995-08-08"},  // newest file on the disc, days after 3.2 (PVD date bogus too)
    {"simpsons", "The Simpsons Screen Saver", "Simpsons", Recipe::ad3zip, "packages/simpsons", kSimpsonsModuleDirs,
     kSimpsonsImages, kSimpsonsRequired, {}, nullptr, {}, "SIMPSONS", "ADXPL310.DLL", "SAX.AFI", kSimpsonsArchives,
     {}, {}, manifest(kSimpsonsKnown), kSimpsonsDownloads, kSimpsonsCovers, "1994-08"},  // modules dated 1994-08-02
    // Every Windows build found dates from 1994-08-20 at the earliest
    // (INTERMIS.EXE); LucasArts announced July 1994 for both platforms. This
    // CD is a later build (files 1994-10), mastered 1995-05-24. It sorts after
    // the Simpsons (1994-08) by registry order on the tie.
    {"swse", "Star Wars Screen Entertainment", "Star Wars", Recipe::intermission, "packages/swse", kSwseModuleDirs,
     kSwseImages, kSwseRequired, {}, nullptr, {}, "SAVER", nullptr, nullptr, kSwseArchives, {}, kSwseNames,
     manifest(kSwseKnown), kSwseDownloads, kSwseCovers, "1994-08", "SWSE", kSwseLoose},
    // The newest files on the disks are dated 1992-11-16 (the modules). Last in
    // the registry, so the first six keep their places (the GUI's per-release
    // command ids go by registry index); first in the catalog's packages list.
    // Some of its modules compose a fixed 640x480 scene (at larger screens
    // The Mission sits top-left with a band; Final Exam and Sickbay sit small
    // in the middle), and the others lay out for whatever screen they get:
    // the catalog gives all 16 that screen, so the release looks as it did at
    // 640x480.
    {"startrek", "Star Trek: The Screen Saver", "Star Trek", Recipe::ad2kwaj, "packages/startrek",
     kStartrekModuleDirs, kStartrekImages, kStartrekRequired, {}, nullptr, {}, "AFTERDRK", nullptr, nullptr,
     kStartrekDiskTags, {}, kStartrekNames, manifest(kStartrekKnown), kStartrekDownloads, kStartrekCovers, "1992-11",
     nullptr, kStartrekLoose, "Star Trek\xAE: The Screen Saver", "640x480", Package::About::ad20},
};

}  // namespace

bool Package::is_deluxe() const { return std::string_view(root) == "FILES"; }

const char* recipe_name(Recipe r) {
  switch (r) {
    case Recipe::tree: return "tree";
    case Recipe::ad3zip: return "ad3zip";
    case Recipe::intermission: return "intermission";
    case Recipe::ad2kwaj: return "ad2kwaj";
  }
  return "?";
}

uint64_t download_size(const Download& d) {
  uint64_t n = d.size;
  for (const DownloadPart& p : d.more_images) n += p.size;
  return n;
}

std::span<const Package> builtin_packages() { return kPackages; }

std::span<const Package> registry_or_builtin(std::span<const Package> registry) {
  return registry.empty() ? builtin_packages() : registry;
}

const Package* find_package(std::string_view id, std::span<const Package> registry) {
  for (const Package& p : registry_or_builtin(registry))
    if (id == p.id) return &p;
  return nullptr;
}

std::string known_releases(std::span<const Package> registry) {
  std::string s;
  for (const Package& p : registry_or_builtin(registry)) {
    if (!s.empty()) s += ", ";
    s += p.title;
  }
  return s;
}

std::vector<std::string> downloadable_packages(std::span<const Package> registry) {
  std::vector<std::string> ids;
  for (const Package& p : registry_or_builtin(registry))
    if (!p.downloads.empty()) ids.push_back(p.id);
  return ids;
}

}  // namespace adw::import
