#include "packages.h"

#include "importer.h"

namespace adw::import {

namespace {

// ---- manifests (generated by gen_known_files.py; sizes and md5s only) --------------

const KnownFile kDeluxeKnown[] = {
#include "known_files.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kAd10Known[] = {
#include "known_files_ad10.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kAd32Known[] = {
#include "known_files_ad32.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kTtKnown[] = {
#include "known_files_tt.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kSimpsonsKnown[] = {
#include "known_files_simpsons.inc"
    {nullptr, 0, nullptr},
};

template <size_t N>
std::span<const KnownFile> manifest(const KnownFile (&a)[N]) {
  return std::span<const KnownFile>(a, N - 1);
}

// ---- deluxe ------------------------------------------------------------------------------

// The md5s of two setup pictures, read from the known images: ADE\PAGE1.BMP
// on the Deluxe CD (28198 bytes, 118x226) and INSTALL\SETUP.BMP on the
// Totally Twisted CD (49314 bytes, 387x251).
constexpr char kDeluxePage1Md5[] = "945259b85a1f0a5e0aedfad53561c838";
constexpr char kTtSetupBmpMd5[] = "3e5eee81009de2a2a432cfabf5d7cfea";

const char* const kDeluxeModuleDirs[] = {"AD40", "ENGINE", "CLASSIC"};
const KnownImage kDeluxeImages[] = {
    {kDeluxeIsoMd5, 400234496, "ISO-9660, Mac/PC hybrid CD", "AD_DELUXE"},
};
const Download kDeluxeDownloads[] = {
    {kDeluxeIsoUrl, kDeluxeIsoFileName, 400234496, kDeluxeIsoMd5, "image"},
};
// Without these three engines neither lane can run anything.
const char* const kDeluxeRequired[] = {"AD40/ADXPL510.DLL", "CLASSIC/ADXPL300.DLL", "ENGINE/OLDMOD16.DLL"};
// The folders under ADE\FILES the hosts use (WALLPAPR is desktop wallpaper).
const char* const kDeluxeCopy[] = {"AD40", "CLASSIC", "ENGINE", "AFI"};

// ---- ad10 --------------------------------------------------------------------------------

const char* const kAd10ModuleDirs[] = {"AD10TH", "ENGINE"};
const KnownImage kAd10Images[] = {
    {"a8d088415d391ce0d3199a831e1b2ad6", 150228992, "ISO-9660 + Joliet, Mac/PC hybrid CD", "AD10TH"},
};
// The only exact copy online (darkened once, restored 2024-07-19).
const Download kAd10Downloads[] = {
    {"https://archive.org/download/ad10th/ad10th.iso", L"ad10th.iso", 150228992, "a8d088415d391ce0d3199a831e1b2ad6",
     "image"},
};
const char* const kAd10Required[] = {"AD10TH/ADXPL510.DLL", "AD10TH/ADXPL300.DLL", "AD10TH/ADXPL40.DLL",
                                     "ENGINE/OLDMOD16.DLL", "ENGINE/AD_SND.DLL",   "ENGINE/AFTERDAR.SCR"};
// GAMES (standalone game EXEs) and WALLPAPR are not screen savers.
const char* const kAd10Copy[] = {"AD10TH", "ENGINE", "AFI"};
// Deluxe's FILES has an AD40; the 10th Anniversary's has none.
const char* const kAd10Absent[] = {"AD40"};
// What the original installers did and the modules depend on (SETUP.INF and
// ENGINE\PREVIOUS.INF): ADXPL40 loads TT_SND.DLL from the AD Data Files root
// only, and the Toasters 2k builds open their music by its installed long
// names.
const Fixup kAd10Fixups[] = {
    {"AD10TH/TT_SND.DLL", "AD10TH/MUSIC/TT_SND.DLL"},
    {"AD10TH/MUSIC/Toasters2k.mid", "AD10TH/TOASTER1.MID"},
    {"AD10TH/MUSIC/Flying Toasters.mid", "AD10TH/TOASTERS.MID"},
    {"AD10TH/MUSIC/Baby Toasters.mid", "AD10TH/BABY.MID"},
};
// An earlier build that SETUP.INF never installs; it would otherwise share
// the installed TOASTER2.AD's name.
const NameOverride kAd10Names[] = {
    {"AD10TH/TOAST2K.AD", "Toasters 2k (early build)"},
};

// ---- ad32 --------------------------------------------------------------------------------

const char* const kAd32ModuleDirs[] = {"AD32"};
const KnownImage kAd32Images[] = {
    {"8b8be6977375fbf4d54146b9d505aa1c", 61693952, "ISO-9660, Mac/PC hybrid CD", "ADW320_C"},
};
// Three byte-identical copies, one file name: the curated one first, the
// uncurated upload last.
const Download kAd32Downloads[] = {
    {"https://archive.org/download/after-dark-v3_2/"
     "After%20Dark%203.2%20%281995%29%28Berkeley%20Systems%29%5BMac-PC%5D.iso",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
    {"https://archive.org/download/berkeley-systems-after-dark-for-windows/berkeley-systems-after-dark-for-windows.iso",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
    {"https://archive.org/download/3x-2634d-923b-452be-6e-0210afa-3547b-9469-after-dark-3.2-nirvana/ADW320_C.ISO",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
};
const char* const kAd32Required[] = {"AD32/ADXPL300.DLL", "ENGINE/AD_SND.DLL", "ENGINE/ADTASK.DLL"};

// ---- tt ----------------------------------------------------------------------------------

const char* const kTtModuleDirs[] = {"TWISTED"};
const KnownImage kTtImages[] = {
    {"541b9cfd744c377263a4ab1a144bdc12", 39784448, "ISO-9660, Mac/PC hybrid CD", "TTW320CD"},
};
const Download kTtDownloads[] = {
    {"https://archive.org/download/TTW320CD/TTW320CD.ISO", L"TTW320CD.ISO", 39784448, "541b9cfd744c377263a4ab1a144bdc12",
     "image"},
};
const char* const kTtRequired[] = {"TWISTED/ADXPL40.DLL", "TWISTED/TT_SND.DLL", "ENGINE/AD_SND.DLL",
                                   "ENGINE/ADTASK.DLL"};

// ---- simpsons ----------------------------------------------------------------------------

const char* const kSimpsonsModuleDirs[] = {"SIMPSONS"};
const KnownImage kSimpsonsImages[] = {
    {"7674adbda6fc5402d4e7a78af14880cc", 2949120, "FAT12 2.88 MB floppy image (both install disks)", ""},
};
// No image of the floppies exists online (the known image is the owner's own
// merge of both disks, with their notes): two ZIPs of the 28 install files,
// every one md5-identical to the floppies' (the readme CHANGES.TXT, which
// the recipe never reads, is missing). Different bytes, so different names.
const Download kSimpsonsDownloads[] = {
    {"https://archive.org/download/SIMPSONS_WIN/SIMPSONS.zip", L"SIMPSONS.zip", 2752575,
     "90a85bf64c971fe65045f1afc6db0eba", "zip"},
    {"https://archive.org/download/AfterDarkSimpsons/After%20Dark%20-%20The%20Simpsons.zip",
     L"After Dark - The Simpsons.zip", 2752010, "1d6083344b16f09e61acf016eca25026", "zip"},
};
const char* const kSimpsonsRequired[] = {"SIMPSONS/ADXPL310.DLL", "SIMPSONS/SIMP_SND.DLL", "ENGINE/AD_SND.DLL",
                                         "ENGINE/ADTASK.DLL"};
// The 15 module archives, spread over both install floppies.
const char* const kSimpsonsArchives[] = {"BURNS.ZIP",    "CHALKBRD.ZIP", "CLOCKS.ZIP",  "GRAFFITI.ZIP", "GRANDPA.ZIP",
                                         "GRASSKRT.ZIP", "HOMEREAT.ZIP", "HOW2DRAW.ZIP", "INS.ZIP",     "KRUSTY.ZIP",
                                         "MLISA.ZIP",    "PHYSICS.ZIP",  "SFILES.ZIP",  "SNOWBALL.ZIP", "STRIVIA.ZIP"};

// ---- box covers (COVERS.md §2.3) ------------------------------------------------------------
//
// Only URLs, md5s, sizes, paths and crops: the pictures are fetched (md5- and
// size-checked) or read from the disc being imported onto the user's machine,
// never shipped. The research behind each row is in
// research/win/pkg/covers/<id>/cover.json (gitignored).

using CK = CoverSource::Kind;

// A download source: an https URL as published, the md5 and size of the file.
constexpr CoverSource cover_download(const char* art, const char* label, const char* credit, const char* url,
                                     const char* md5, uint64_t size, const wchar_t* file_name, Crop crop = {}) {
  return CoverSource{CK::download, art, label, credit, url, md5, size, file_name, nullptr, nullptr, 0, 0, crop};
}
// A picture on the source being imported (resource 2 = an NE/PE RT_BITMAP).
constexpr CoverSource cover_disc(const char* art, const char* label, const char* credit, const char* path,
                                 const char* path_md5, Crop crop = {}, uint16_t resource_type = 0,
                                 uint16_t resource_id = 0) {
  return CoverSource{CK::disc, art, label, credit, nullptr, nullptr, 0, nullptr, path, path_md5, resource_type,
                     resource_id, crop};
}

// Deluxe: the box front from Berkeley Systems' own product page (1997, through
// the Wayback Machine; 162x195, and a tile is never shown larger than 160x200),
// else the setup wizard's portrait art on the disc, else the Internet
// Archive's scan of the disc label (the same item as the ISO).
const CoverSource kDeluxeCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113325id_/"
                   "http://www.berksys.com:80/products/afterdark/box.deluxe.gif",
                   "abb5ea84262cc6a2badea016f69cc7e8", 19460, L"berksys_box.deluxe.gif"),
    cover_disc("panel", "Setup art", "your disc", "ADE/PAGE1.BMP", kDeluxePage1Md5),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/after-dark-4-deluxe/disc.jpg",
                   "0b5104351ae6fa60da6d48164e8f548e", 737758, L"after-dark-4-deluxe_disc.jpg"),
};
// 10th Anniversary: the disc-label scan in the ISO's item, else the setup
// wizard's art (pages 1-6 are byte-identical). The box art the user owns has
// no downloadable copy: it becomes the cover only through --set-cover.
const CoverSource kAd10Covers[] = {
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/ad10th/01_ad10_cd.jpg",
                   "e1e77b74ccc9bcd4e5b818f841f0614d", 376876, L"ad10th_01_ad10_cd.jpg"),
    cover_disc("panel", "Setup art", "your disc", "ADE/PAGE1.BMP", "30f247d08fe8a4fd394658a3c4564a06"),
};
// 3.2: no box scan of 3.0 or 3.2 exists; the installer splash comes first,
// cropped above its warning and copyright rows, then two scans of the label.
const CoverSource kAd32Covers[] = {
    cover_disc("splash", "Installer art", "your disc", "INSTALL/SETUP.BMP", "67e76581f69bcfdb62ef1c7ff61fc426",
               Crop{0, 0, 387, 183}),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/after-dark-v3_2/disc.jpg",
                   "68f2aad89dcdc1fdbcb3419ab42077f9", 349982, L"after-dark-v3_2_disc.jpg"),
    cover_download("disc", "Disc label", "Internet Archive",
                   "https://archive.org/download/berkeley-systems-after-dark-for-windows/"
                   "berkeley-systems-after-dark-for-windows.png",
                   "f2fdf32138f96da06f8d348af059d712", 1857714, L"berkeley-systems-after-dark-for-windows.png"),
};
// Totally Twisted: the box front from Berkeley Systems' product page (1997,
// through the Wayback Machine; 127x162, the retail box's art), else the box
// front of Sierra's later edition from The Sierra Chest (through the Wayback
// Machine; 498x599), else the installer splash, cropped above its warning
// text, else the TTW320CD item's TIFF scan of the disc (2840x2888).
const CoverSource kTtCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113451id_/"
                   "http://www.berksys.com:80/products/afterdark/box.twistedL.jpg",
                   "5aa9478d761a580f1d9006ee41d0cd3f", 26382, L"berksys_box.twistedL.jpg"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20230422055429id_/"
                   "https://www.sierrachest.com/gfx/games/AfterDarkTotallyTwisted/box/01_front.JPG",
                   "3f87e84e3d86d7a2d6f96c86a8102452", 53679, L"sierrachest_AfterDarkTotallyTwisted_01_front.jpg"),
    cover_disc("splash", "Installer art", "your disc", "INSTALL/SETUP.BMP", kTtSetupBmpMd5, Crop{0, 0, 387, 204}),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/TTW320CD/TTW320CD.tif",
                   "ec19d74fd2ac46d4bc8f6021ad0011e6", 24632572, L"TTW320CD.tif"),
};
// The Simpsons: the box front (Fox's art: fetched onto the user's machine
// only, never bundled), from Wikisimpsons, else the Wayback Machine's copy of
// the full-box scan it was cut from; else the installer splash in SETUP.EXE.
const CoverSource kSimpsonsCovers[] = {
    cover_download("box", "Box front", "Wikisimpsons",
                   "https://static.simpsonswiki.com/images/7/72/The_Simpsons_Screen_Saver.png",
                   "47f4619da9e79b126a4fb45770f0e649", 1011608, L"The_Simpsons_Screen_Saver.png"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20250715075938id_/"
                   "https://www.whipassgaming.com/images/deadsections/mac/simpsonsfullbox.jpg",
                   "94db22db1e89b3ff2fdb97e610056602", 484234, L"simpsonsfullbox.jpg", Crop{0, 0, 600, 776}),
    cover_disc("splash", "Installer art", "your disks", "SETUP.EXE", "980867b7ab5394b09adad725d375ba95",
               Crop{0, 0, 387, 172}, 2, 7500),
};

const Package kPackages[] = {
    {"deluxe", "After Dark 4.0 Deluxe", "Deluxe", Recipe::tree, "FILES", kDeluxeModuleDirs, kDeluxeImages,
     kDeluxeRequired, kDeluxeCopy, nullptr, {}, nullptr, nullptr, nullptr, {}, {}, {}, manifest(kDeluxeKnown),
     kDeluxeDownloads, kDeluxeCovers, "1996-10"},  // disc mastered 1996-10-12; modules dated 1996-09
    {"ad10", "After Dark 10th Anniversary", "10th Anniversary", Recipe::tree, "packages/ad10", kAd10ModuleDirs,
     kAd10Images, kAd10Required, kAd10Copy, "AD10TH/ADXPL40.DLL", kAd10Absent, nullptr, nullptr, nullptr, {},
     kAd10Fixups, kAd10Names, manifest(kAd10Known), kAd10Downloads, kAd10Covers, "1999-09"},  // disc mastered 1999-09-06
    {"ad32", "After Dark 3.2", "After Dark 3.2", Recipe::ad3zip, "packages/ad32", kAd32ModuleDirs, kAd32Images,
     kAd32Required, {}, nullptr, {}, "AD32", "ADXPL300.DLL", "AD3.AFI", {}, {}, {}, manifest(kAd32Known),
     kAd32Downloads, kAd32Covers, "1995-08-02"},  // newest file on the disc (its PVD date is a bogus 1993)
    {"tt", "Totally Twisted After Dark", "Totally Twisted", Recipe::ad3zip, "packages/tt", kTtModuleDirs, kTtImages,
     kTtRequired, {}, nullptr, {}, "TWISTED", "ADXPL40.DLL", "PHLEM.AFI", {}, {}, {}, manifest(kTtKnown),
     kTtDownloads, kTtCovers, "1995-08-08"},  // newest file on the disc, days after 3.2 (PVD date bogus too)
    {"simpsons", "The Simpsons Screen Saver", "Simpsons", Recipe::ad3zip, "packages/simpsons", kSimpsonsModuleDirs,
     kSimpsonsImages, kSimpsonsRequired, {}, nullptr, {}, "SIMPSONS", "ADXPL310.DLL", "SAX.AFI", kSimpsonsArchives,
     {}, {}, manifest(kSimpsonsKnown), kSimpsonsDownloads, kSimpsonsCovers, "1994-08"},  // modules dated 1994-08-02
};

}  // namespace

bool Package::is_deluxe() const { return std::string_view(root) == "FILES"; }

std::span<const Package> builtin_packages() { return kPackages; }

std::span<const Package> registry_or_builtin(std::span<const Package> registry) {
  return registry.empty() ? builtin_packages() : registry;
}

const Package* find_package(std::string_view id, std::span<const Package> registry) {
  for (const Package& p : registry_or_builtin(registry))
    if (id == p.id) return &p;
  return nullptr;
}

std::string known_releases(std::span<const Package> registry) {
  std::string s;
  for (const Package& p : registry_or_builtin(registry)) {
    if (!s.empty()) s += ", ";
    s += p.title;
  }
  return s;
}

std::vector<std::string> downloadable_packages(std::span<const Package> registry) {
  std::vector<std::string> ids;
  for (const Package& p : registry_or_builtin(registry))
    if (!p.downloads.empty()) ids.push_back(p.id);
  return ids;
}

}  // namespace adw::import
